name: robotfindsci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependency packages
      run: sudo apt-get -y install build-essential gnulib libncurses-dev texinfo texlive-latex-recommended pandoc
    - name: autoreconf
      run: autoreconf -ifv
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Upload dist
      uses: actions/upload-artifact@v2
      with:
        name: robotfindskitten-dist-${{ github.job }}-${{ github.run_id }}.${{ github.run_number }}
        path: robotfindskitten-*.tar.gz
